// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // vJobCandidateEmployment
    [Table("vJobCandidateEmployment", Schema = "HumanResources")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class HumanResources_VJobCandidateEmployment
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"JobCandidateID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Job candidate ID")]
        public int JobCandidateId { get; set; } // JobCandidateID (Primary key)

        [Column(@"Emp.StartDate", Order = 2, TypeName = "datetime")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Emp start date")]
        public System.DateTime? Emp46StartDate { get; set; } // Emp.StartDate

        [Column(@"Emp.EndDate", Order = 3, TypeName = "datetime")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Emp end date")]
        public System.DateTime? Emp46EndDate { get; set; } // Emp.EndDate

        [Column(@"Emp.OrgName", Order = 4, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Emp org name")]
        public string Emp46OrgName { get; set; } // Emp.OrgName (length: 100)

        [Column(@"Emp.JobTitle", Order = 5, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Emp job title")]
        public string Emp46JobTitle { get; set; } // Emp.JobTitle (length: 100)

        [Column(@"Emp.Responsibility", Order = 6, TypeName = "nvarchar(max)")]
        [Display(Name = "Emp responsibility")]
        public string Emp46Responsibility { get; set; } // Emp.Responsibility

        [Column(@"Emp.FunctionCategory", Order = 7, TypeName = "nvarchar(max)")]
        [Display(Name = "Emp function category")]
        public string Emp46FunctionCategory { get; set; } // Emp.FunctionCategory

        [Column(@"Emp.IndustryCategory", Order = 8, TypeName = "nvarchar(max)")]
        [Display(Name = "Emp industry category")]
        public string Emp46IndustryCategory { get; set; } // Emp.IndustryCategory

        [Column(@"Emp.Loc.CountryRegion", Order = 9, TypeName = "nvarchar(max)")]
        [Display(Name = "Emp loc country region")]
        public string Emp46Loc46CountryRegion { get; set; } // Emp.Loc.CountryRegion

        [Column(@"Emp.Loc.State", Order = 10, TypeName = "nvarchar(max)")]
        [Display(Name = "Emp loc state")]
        public string Emp46Loc46State { get; set; } // Emp.Loc.State

        [Column(@"Emp.Loc.City", Order = 11, TypeName = "nvarchar(max)")]
        [Display(Name = "Emp loc city")]
        public string Emp46Loc46City { get; set; } // Emp.Loc.City
    }

}
// </auto-generated>
