// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // UnitMeasure
    ///<summary>
    /// Unit of measure lookup table.
    ///</summary>
    [Table("UnitMeasure", Schema = "Production")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Production_UnitMeasure
    {

        ///<summary>
        /// Primary key.
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"UnitMeasureCode", Order = 1, TypeName = "nchar")]
        [Index(@"PK_UnitMeasure_UnitMeasureCode", 1, IsUnique = true, IsClustered = true)]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(3)]
        [StringLength(3)]
        [Key]
        [Display(Name = "Unit measure code")]
        public string UnitMeasureCode { get; set; } // UnitMeasureCode (Primary key) (length: 3)

        ///<summary>
        /// Unit of measure description.
        ///</summary>
        [Column(@"Name", Order = 2, TypeName = "nvarchar")]
        [Index(@"AK_UnitMeasure_Name", 1, IsUnique = true, IsClustered = false)]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 50)

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        [Column(@"ModifiedDate", Order = 3, TypeName = "datetime")]
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child Production_BillOfMaterials where [BillOfMaterials].[UnitMeasureCode] point to this entity (FK_BillOfMaterials_UnitMeasure_UnitMeasureCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Production_BillOfMaterial> Production_BillOfMaterials { get; set; } // BillOfMaterials.FK_BillOfMaterials_UnitMeasure_UnitMeasureCode
        /// <summary>
        /// Child Production_Products where [Product].[SizeUnitMeasureCode] point to this entity (FK_Product_UnitMeasure_SizeUnitMeasureCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Production_Product> Production_Products_SizeUnitMeasureCode { get; set; } // Product.FK_Product_UnitMeasure_SizeUnitMeasureCode
        /// <summary>
        /// Child Production_Products where [Product].[WeightUnitMeasureCode] point to this entity (FK_Product_UnitMeasure_WeightUnitMeasureCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Production_Product> Production_Products_WeightUnitMeasureCode { get; set; } // Product.FK_Product_UnitMeasure_WeightUnitMeasureCode
        /// <summary>
        /// Child Purchasing_ProductVendors where [ProductVendor].[UnitMeasureCode] point to this entity (FK_ProductVendor_UnitMeasure_UnitMeasureCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Purchasing_ProductVendor> Purchasing_ProductVendors { get; set; } // ProductVendor.FK_ProductVendor_UnitMeasure_UnitMeasureCode

        public Production_UnitMeasure()
        {
            ModifiedDate = System.DateTime.Now;
            Production_BillOfMaterials = new System.Collections.Generic.List<Production_BillOfMaterial>();
            Production_Products_SizeUnitMeasureCode = new System.Collections.Generic.List<Production_Product>();
            Production_Products_WeightUnitMeasureCode = new System.Collections.Generic.List<Production_Product>();
            Purchasing_ProductVendors = new System.Collections.Generic.List<Purchasing_ProductVendor>();
        }
    }

}
// </auto-generated>
