// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // ProductModelIllustration
    ///<summary>
    /// Cross-reference table mapping product models and illustrations.
    ///</summary>
    [Table("ProductModelIllustration", Schema = "Production")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Production_ProductModelIllustration
    {

        ///<summary>
        /// Primary key. Foreign key to ProductModel.ProductModelID.
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ProductModelID", Order = 1, TypeName = "int")]
        [Index(@"PK_ProductModelIllustration_ProductModelID_IllustrationID", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Product model ID")]
        public int ProductModelId { get; set; } // ProductModelID (Primary key)

        ///<summary>
        /// Primary key. Foreign key to Illustration.IllustrationID.
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"IllustrationID", Order = 2, TypeName = "int")]
        [Index(@"PK_ProductModelIllustration_ProductModelID_IllustrationID", 2, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Illustration ID")]
        public int IllustrationId { get; set; } // IllustrationID (Primary key)

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        [Column(@"ModifiedDate", Order = 3, TypeName = "datetime")]
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent Production_Illustration pointed by [ProductModelIllustration].([IllustrationId]) (FK_ProductModelIllustration_Illustration_IllustrationID)
        /// </summary>
        [ForeignKey("IllustrationId"), Required] public virtual Production_Illustration Production_Illustration { get; set; } // FK_ProductModelIllustration_Illustration_IllustrationID

        /// <summary>
        /// Parent Production_ProductModel pointed by [ProductModelIllustration].([ProductModelId]) (FK_ProductModelIllustration_ProductModel_ProductModelID)
        /// </summary>
        [ForeignKey("ProductModelId"), Required] public virtual Production_ProductModel Production_ProductModel { get; set; } // FK_ProductModelIllustration_ProductModel_ProductModelID

        public Production_ProductModelIllustration()
        {
            ModifiedDate = System.DateTime.Now;
        }
    }

}
// </auto-generated>
