// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Context
{

    // vSalesPersonSalesByFiscalYears
    [Table("vSalesPersonSalesByFiscalYears", Schema = "Sales")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Sales_VSalesPersonSalesByFiscalYear
    {
        [Column(@"SalesPersonID", Order = 1, TypeName = "int")]
        [Display(Name = "Sales person ID")]
        public int? SalesPersonId { get; set; } // SalesPersonID

        [Column(@"FullName", Order = 2, TypeName = "nvarchar")]
        [MaxLength(152)]
        [StringLength(152)]
        [Display(Name = "Full name")]
        public string FullName { get; set; } // FullName (length: 152)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"JobTitle", Order = 3, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        [Display(Name = "Job title")]
        public string JobTitle { get; set; } // JobTitle (Primary key) (length: 50)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"SalesTerritory", Order = 4, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        [Display(Name = "Sales territory")]
        public string SalesTerritory { get; set; } // SalesTerritory (Primary key) (length: 50)

        [Column(@"2002", Order = 5, TypeName = "money")]
        [DataType(DataType.Currency)]
        [Display(Name = "2002")]
        public decimal? C2002 { get; set; } // 2002

        [Column(@"2003", Order = 6, TypeName = "money")]
        [DataType(DataType.Currency)]
        [Display(Name = "2003")]
        public decimal? C2003 { get; set; } // 2003

        [Column(@"2004", Order = 7, TypeName = "money")]
        [DataType(DataType.Currency)]
        [Display(Name = "2004")]
        public decimal? C2004 { get; set; } // 2004
    }

}
// </auto-generated>
