// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using Interfaces;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // vJobCandidateEducation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class HumanResources_VJobCandidateEducationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<HumanResources_VJobCandidateEducation>
    {
        public HumanResources_VJobCandidateEducationConfiguration()
            : this("HumanResources")
        {
        }

        public HumanResources_VJobCandidateEducationConfiguration(string schema)
        {
            Property(x => x.Edu46Level).IsOptional();
            Property(x => x.Edu46StartDate).IsOptional();
            Property(x => x.Edu46EndDate).IsOptional();
            Property(x => x.Edu46Degree).IsOptional();
            Property(x => x.Edu46Major).IsOptional();
            Property(x => x.Edu46Minor).IsOptional();
            Property(x => x.Edu46Gpa).IsOptional();
            Property(x => x.Edu46GpaScale).IsOptional();
            Property(x => x.Edu46School).IsOptional();
            Property(x => x.Edu46Loc46CountryRegion).IsOptional();
            Property(x => x.Edu46Loc46State).IsOptional();
            Property(x => x.Edu46Loc46City).IsOptional();
        }
    }

}
// </auto-generated>
