// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using Interfaces;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // ProductVendor
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Purchasing_ProductVendorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Purchasing_ProductVendor>
    {
        public Purchasing_ProductVendorConfiguration()
            : this("Purchasing")
        {
        }

        public Purchasing_ProductVendorConfiguration(string schema)
        {
            Property(x => x.StandardPrice).HasPrecision(19,4);
            Property(x => x.LastReceiptCost).IsOptional().HasPrecision(19,4);
            Property(x => x.LastReceiptDate).IsOptional();
            Property(x => x.OnOrderQty).IsOptional();
            Property(x => x.UnitMeasureCode).IsFixedLength();

        }
    }

}
// </auto-generated>
