// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // vVendorWithAddresses
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Purchasing_VVendorWithAddressConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Purchasing_VVendorWithAddress>
    {
        public Purchasing_VVendorWithAddressConfiguration()
            : this("Purchasing")
        {
        }

        public Purchasing_VVendorWithAddressConfiguration(string schema)
        {
            Property(x => x.AddressLine2).IsOptional();
        }
    }

}
// </auto-generated>
