// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // vSalesPersonSalesByFiscalYears
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Sales_VSalesPersonSalesByFiscalYearConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Sales_VSalesPersonSalesByFiscalYear>
    {
        public Sales_VSalesPersonSalesByFiscalYearConfiguration()
            : this("Sales")
        {
        }

        public Sales_VSalesPersonSalesByFiscalYearConfiguration(string schema)
        {
            Property(x => x.SalesPersonId).IsOptional();
            Property(x => x.FullName).IsOptional();
            Property(x => x.C2002).IsOptional().HasPrecision(19,4);
            Property(x => x.C2003).IsOptional().HasPrecision(19,4);
            Property(x => x.C2004).IsOptional().HasPrecision(19,4);
        }
    }

}
// </auto-generated>
