// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using Interfaces;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // vPersonDemographics
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Sales_VPersonDemographicConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Sales_VPersonDemographic>
    {
        public Sales_VPersonDemographicConfiguration()
            : this("Sales")
        {
        }

        public Sales_VPersonDemographicConfiguration(string schema)
        {
            Property(x => x.TotalPurchaseYtd).IsOptional().HasPrecision(19,4);
            Property(x => x.DateFirstPurchase).IsOptional();
            Property(x => x.BirthDate).IsOptional();
            Property(x => x.MaritalStatus).IsOptional();
            Property(x => x.YearlyIncome).IsOptional();
            Property(x => x.Gender).IsOptional();
            Property(x => x.TotalChildren).IsOptional();
            Property(x => x.NumberChildrenAtHome).IsOptional();
            Property(x => x.Education).IsOptional();
            Property(x => x.Occupation).IsOptional();
            Property(x => x.HomeOwnerFlag).IsOptional();
            Property(x => x.NumberCarsOwned).IsOptional();
        }
    }

}
// </auto-generated>
